### ISSUE TITLE
Uploaded file truncated to 4GB size

### ISSUE THREAD

**Issue by Halama** [keboola/docker-rstudio#1]
Jak nasimulovat:
 - uploadnnout zip který obsahuje soubor větší než 4GB
 - soubor se po uploadu rozbalí a na disku bude ořezaný na 4GB

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/27685954-c82caea0-5cd0-11e7-9bbd-2b303b0314a3.png)

**Comment by Halama** [comment]
https://stackoverflow.com/questions/42740206/r-possible-truncation-of-4gb-file :(

**Comment by Halama** [comment]
zkusím to gzipnout a jestli to projde tak bych to jenom hodil někam do dokumentace.

**Comment by Halama** [comment]
Zapomněl jsem dodat že se to týká uploadů přímo přes UI Rstudia, pokud člověk uploaduje zip tak ho to po nahrání automaticky rozbalí a vten moment to rozbije:
![image](https://user-images.githubusercontent.com/903531/27783798-ea3857ec-5fd7-11e7-90a7-b0f606f1fd6e.png)

**Comment by odinuv** [comment]
Aha!, no ale tak to je hroznej antipattern nahravat 4gb zip uploadem, ma si ho tam hodit pres storage files

**Comment by Halama** [comment]
jo to asi jo. tak muzeme nejspis zavrit.

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/connection-docs/commit/a1b62c539a8ab98f25761af4ba82d5637fe425e1
